### ISSUE TITLE
Basic setup - 404

### ISSUE THREAD

**Issue by ggstrader** [invariant/obsidian-archivebox-plugin#1]
First, I realize setting up archivebox is out of the scope of this plugin, but it wouldn't hurt to have a minimal reproducible example in the README of how to use the plugin start to finish.

What I've done (Windows 10):
```
mkdir ~/archivebox
cd ~/archivebox
Invoke-WebRequest -OutFile 'docker-compose.yml' 'https://raw.githubusercontent.com/ArchiveBox/ArchiveBox/master/docker-compose.yml'
docker-compose run archivebox init --setup
docker-compose up
```

Everything seems to be working on the archivebox side of things. However I get a 404 in the obsidian dev console.
All I've done is change these settings:
![image](https://user-images.githubusercontent.com/101308963/216581096-4dde2b48-b3bf-4e75-8b94-55004db896b6.png)
Originally with "Ignore RFC1918 Addresses" *on*, I get the 404. I assumed that wouldn't have anything to do with the URI setting, but toggled it off just to see. Now I no longer get the 404, but it still isn't actually archiving anything in the notes. I see that the plugin finds the links because it says it's "Ignoring already matched..." and "Adding..." But adding new links does nothing, and none of them show up on the server.

**Comment by invariant** [comment]
There's one bug here for sure, maybe two. Thanks for your report. I'll try to investigate this over the weekend.

First, the system tries to cache already-submitted URIs so it doesn't do it again, but it is not appropriately handling the error on submission (i.e., it's receiving) - that's why you're seeing the "Ignoring already matched" - but those weren't submitted properly. As for the 404, there's a chance that the URI is being composed incorrectly.

Having a minimal docker setup would also help for test cases. Could you provide me with more information about your environment to make this easier for me to debug?

1. Seems you're using Windows as your base OS, as that's Powershell?
2. What version of Docker Desktop are you using?
3. What version of Obsidian are you using?
4. Is `username` an ArchiveBox superuser? Does this user have submission access to `/add/` ? and can view admin pages?

"Ignore RFC1918 Addresses" actually doesn't include loopback, and it's only for link submission - it's basically meant so that you don't submit archives for links to things already on your LAN. ArchiveBox can exist at anything that passes the URL filter in the JavaScript `URL` object.

**Comment by invariant** [comment]
OK, made progress on this earlier than I had expected.

### Bug 1. Incorrect conditional in `main.ts` causing settings validation failure

[main.ts#L180](https://github.com/invariant/obsidian-archivebox-plugin/blob/main/main.ts#L180) contained an incorrect conditional check when validating configuration settings, which is why the plugin failed to work in cases in which RFC1918 address ignore was disabled, as a configuration failure blocks the process.

**Fix**: Fixed conditional in `validateSettings`.

### Bug 2. Cached URIs would cache even if an `/add` request failed.

In order to not spam the ArchiveBox server - even though it does deduplication - the plugin will keep track of URIs it has sent to ArchiveBox as `SHA256(URI)` keys in a JS object. This performance optimisation cuts down on request sizes, but it also did not appropriately handle a failed request; all URI submissions were treated as successful and thus the archive could be lossy.

**Fix**: Adding URIs to the URI cache is now done after the promise for axios has resolved in the `addUrlsToArchiveBox` method.
**Feature**: Created a setting to disable URI caching to provide extra resilience against this failure in the future, or if you'd rather just let ArchiveBox deduplicate URIs that already exist in the archive.


### External Issue 1. ArchiveBox v0.6.2 (aka `master`) is not CSRF-exempt.

The `docker-compose.yml` that you're using, i.e. the last stable `master` - does not allow for the use of the ArchiveBox browser plugin or Rest API because the `/add` endpoint change to [allow for the browser extension wasn't merged yet](https://github.com/ArchiveBox/ArchiveBox/pull/777). There is [no stable API](https://github.com/ArchiveBox/ArchiveBox/issues/496) either. Thus for this plugin to work, you need to be running `dev` or at least the commit hash that merged PR 777. My own `docker-compose.yml` uses `archivebox/archivebox:latest`, which you'd assume was the latest _stable_, but is actually an unstable dev branch committed as tag `latest` about 9 months ago.

**Workaround**: Use `archivebox/archivebox:latest`, or `archivebox/archivebox:dev` in your `docker-compose.yml` and ignore what ArchiveBox has written.
**"Fix"**: Added documentation explaining ArchiveBox's general instability, a barebones `docker-compose.yml` configuration that exactly matches my own.

### Not Reproducible: 404

I can't reproduce getting a `404` ever. I ran both the provided `docker-compose.yml` and then my modified one (using `archivebox/archivebox:latest` but no 404 ever appeared for me as it did for you. I ran the plugin against a local copy on port 8000 as well as my production (remote) instance. 

**Feature**: In order to give more verbose debug information, I added a "Debug Mode" flag to the control panel that will print more verbose `console.log`s to help troubleshoot. This does include semi-sensitive information like a partially redacted session token, so it's advised not to keep it on, but does give more information if other users have a problem.


### Resolution

`dev` will be merged and published as `1.0.1` later this weekend once it has passed further validation testing. @ggstrader please try the [dev]() branch if you have an Obsidian development environment set up and see if this works for you. It's working for me.

**Comment by ggstrader** [comment]
@invariant that's awesome! I'll test it sometime today or tomorrow.

**Comment by ggstrader** [comment]
@invariant finally had an opportunity to test, everything's good on my end, thanks! Lmk if you add a way to tip to show appreciation

**Comment by ggstrader** [comment]
@invariant one more thing, I think the logging messages should be moved to the debug mode so the console isn't filled with "Ignoring already matched..."

**Comment by invariant** [comment]
@ggstrader Yeah, that makes sense. I'll make the change in dev and just merge it in 1.0.2 with other changes, as it's not blocking any functionality at this time and I don't want to roll a new version for a small fix.

As for a tip: I don't have ko-fi fully set up right now, but if you'd like to show some appreciation, please donate some time, resources or currency to a local food bank, homeless support group, or other such community charity facility that's local to you.
